### ISSUE TITLE
Installing gem in docker takes a lot of time

### ISSUE THREAD

**Issue by nexxus-vi** [yfxie/active_storage_variantt#2]
Hi @yfxie, i'm using your gem to generate image variants in an application with `ruby 2.6.6` and `rails 6.1.4.6`
When installing the gem on my pc everything is fast and smooth, but when in Docker the gem's installation time takes an average of 200 seconds. I don't know how to debug this strange behaviour, do you have any hint?

**Comment by yfxie** [comment]
Hi @xxz3 

This gem only depends on rails. I think 200 seconds should be a normal case to install all gems. Not only this gem, but any changes to your Gemfile will also let docker run the entire bundle install again.

So you can try removing this gem or adding an empty line to your Gemfile I believe it will take 200 seconds to run install.

**Comment by nexxus-vi** [comment]
I'm sorry, as docker logs were stuck on `'installing active_storage_variant'` i tought it was installing this gem for so long. My fault 🙇🏻‍♂️
